aktualneprojektkamil/urls.py
# Uncomment next two lines to enable admin:

from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Reservation Management System API",
        default_version='v1',
        description="Description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="email@email.com"),
        license=openapi.License(name="BSD License"),
        ),
    public=True,
    permission_classes=(permissions.AllowAny,))


urlpatterns = [

   
    url(r'admin/', admin.site.urls),
    url(r'', include('ideass.urls')),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

]

ideass/urls.py
from rest_framework import routers
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import HomeView, PlaceViewSet, BookingViewSet, BookingList, BookingAdd, BookingEdit, PlaceList, PlaceAdd,\
    PlaceEdit, SearchViewSet, BookingSearch, register


app_name = 'ideass'
router = routers.DefaultRouter()
router.register('places', PlaceViewSet)
router.register('bookings', BookingViewSet)
router.register('search', SearchViewSet, basename='search')

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', register, name="register"),
    url(r'^book/$', BookingAdd.as_view(), name="book"),
    url(r'^bookings/$', BookingList.as_view(), name='bookings'),
    url(r'^bookings/(?P<pk>[0-9]+)/$', BookingEdit.as_view()),
    url(r'^place_add/$', PlaceAdd.as_view(), name='place_add'),
    url(r'^place/$', PlaceList.as_view(), name='places'),
    url(r'^places/(?P<number>[0-9]+)/$', PlaceEdit.as_view()),
    url(r'^search/$', BookingSearch.as_view(), name='search'),
    url(r'^place_edit/$', PlaceEdit.as_view(), name='place_edit'),
]

ideass/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from .config import PLACE_CATEGORIES, PLACE_PRICES


class Place(models.Model):
    number = models.IntegerField(unique=True, primary_key=True)
    category = models.PositiveSmallIntegerField(choices=PLACE_CATEGORIES)


    def __str__(self):
        return f'Place {self.number}, class {PLACE_CATEGORIES[self.category - 1][1]}'

    @property
    def get_category(self):
        return PLACE_CATEGORIES[self.category - 1][1]


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    surname = models.CharField(max_length=30)
    places = models.ManyToManyField(Place)
    check_in = models.DateField()
    check_out = models.DateField()
    created = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return f'{self.user}, {self.surname} has booked {[x for x in self.places.all()]}, from {self.check_in} to {self.check_out}'

    @property
    def get_place(self):
        return f'{[x for x in self.places.values_list("number", flat=True)]}'[1:-1]

    def get_booking_time(self):
        return int((self.check_out - self.check_in).days)

    def get_booking_price(self):
        place_categories = [x.get_category for x in self.places.all()]
        return sum([self.get_booking_time() * PLACE_PRICES[x] for x in place_categories])

ideass/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group


class SignUpForm(UserCreationForm):
    # email = forms.EmailField(required=True)
    class Meta:
        model = User
        # fields = ("username", "email", "password1", "password2")
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        # user.email = self.cleaned_data['email']
        if commit:
            user.save()
            group_client, _ = Group.objects.get_or_create(name='Client')
            group_client.user_set.add(user)
        return user

ideass/views.py
from datetime import datetime
from json import dumps
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import get_object_or_404, redirect
from rest_framework import viewsets, status
from rest_framework.mixins import ListModelMixin
from rest_framework.viewsets import GenericViewSet
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.generics import GenericAPIView
from drf_yasg.utils import swagger_auto_schema
from .models import Place, Booking
from .serializers import PlaceSerializer, BookingSerializer, SearchBookingSerializer
from .permissions import HasGroupPermission, REQ_GROUPS_BOOKINGS, REQ_GROUPS_BOOKINGS_UPDATE, REQ_GROUPS_PLACE
from .forms import SignUpForm
from .config import PLACE_PRICES
from aktualneprojektkamil.settings import REGISTRATION_OPEN

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %%%%%%%%%%%%%%%%%%%%%%%%% API VIEWS %%%%%%%%%%%%%%%%%%%%%%%%%%
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
class PlaceViewSet(viewsets.ModelViewSet):
    queryset = Place.objects.all()
    serializer_class = PlaceSerializer
    http_method_names = ['get', 'post', 'head', 'put', 'delete']
    permission_classes = (HasGroupPermission,)
    required_groups = REQ_GROUPS_PLACE
    template_name = 'bookings.html'
    # place duplication is prevented by RoomSerializer internally with is_valid()

    def destroy(self, request, *args, **kwargs):  # DELETE
        instance = get_object_or_404(Place, number=kwargs['pk'])  # pk is just place number from url
        if Booking.objects.filter(places=instance).exists():
            return Response({'error': 'This place is used by at least one booking, cannot be deleted'},
                            status=status.HTTP_403_FORBIDDEN)
        return super().destroy(request, *args, **kwargs)

class BookingViewSet(viewsets.ModelViewSet):
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer
    http_method_names = ['get', 'post', 'head', 'put', 'delete']
    permission_classes = (HasGroupPermission,)
    required_groups = REQ_GROUPS_BOOKINGS

    def create(self, request, *args, **kwargs):  # POST
        serializer = BookingSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            return super().create(request, *args, **kwargs)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def update(self, request, *args, **kwargs):  # PUT
        instance = self.get_object()
        serializer = BookingSerializer(instance=instance, data=request.data, context={'request': request})
        if serializer.is_valid():
            return super().update(request, *args, **kwargs)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class SearchViewSet(GenericViewSet, ListModelMixin):
    serializer_class = SearchBookingSerializer
    http_method_names = ['get']
    permission_classes = (HasGroupPermission,)
    required_groups = {'GET': ['Staff']}

    def get_queryset(self):
        queryset = Booking.objects.all()
        params = self.request.query_params.copy().dict()
        params = {key: value for key, value in params.items() if value != ''}
        if 'places' in params.keys():
            places = params['places'].split(',')
            for place in places:
                queryset = queryset.filter(places=place).distinct()
            del params['places']
        if 'created' in params.keys():
            created = datetime.strptime(params['created'], '%Y-%m-%d')
            queryset = queryset.filter(created__date=created).distinct()
            del params['created']
        queryset = queryset.filter(**params).distinct()
        return queryset

    @swagger_auto_schema(query_serializer=SearchBookingSerializer)  # just to fix schemas in swagger
    def list(self, request, *args, **kwargs):
        serializer = SearchBookingSerializer(data=self.request.data, context={'request': self.request})
        if serializer.is_valid():
            return super().list(self)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %%%%%%%%%%%%%%%%%%%%%%% FRONTEND VIEWS %%%%%%%%%%%%%%%%%%%%%%%
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

class HomeView(TemplateView):
    template_name = 'home.html'

def register(request):  # FBV just once for simplicity here
    context = {}
    form = SignUpForm(request.POST or None)
    if request.method == "POST":
        if REGISTRATION_OPEN is False:
            messages.warning(request, f'Registrations are currently disabled!')
            return render(request, 'home.html')
        else:
            if form.is_valid():
                user = form.save()
                login(request, user)
                messages.success(request, f'Registered successfully!')
                return render(request, 'home.html')
    context['form'] = form
    context['REGISTRATION_OPEN'] = REGISTRATION_OPEN
    return render(request, 'registration/register.html', context)


class RoomGenericAPIView(GenericAPIView):
    schema = None  # to hide non-api views from swagger
    style = {'template_pack': 'rest_framework/vertical/'}
    renderer_classes = [TemplateHTMLRenderer]
    base_viewset = PlaceViewSet
    permission_classes = base_viewset.permission_classes


class BookingGenericAPIView(GenericAPIView):
    schema = None  # to hide non-api views from swagger
    style = {'template_pack': 'rest_framework/vertical/'}
    renderer_classes = [TemplateHTMLRenderer]
    base_viewset = BookingViewSet
    permission_classes = base_viewset.permission_classes

class PlaceList(RoomGenericAPIView):
    template_name = 'places.html'
    required_groups = REQ_GROUPS_PLACE

    def get(self, request):
        queryset = Place.objects.all()
        return Response({'places': queryset})

class PlaceAdd(RoomGenericAPIView):
    template_name = 'place_add.html'
    required_groups = REQ_GROUPS_PLACE

    def get(self, request):
        serializer = PlaceSerializer
        return Response({'serializer': serializer, 'style': self.style})

    def post(self, request):
        serializer = RoomSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            messages.success(request, f'Place successfully added!')
            return redirect('/places/')
        return Response({'serializer': serializer, 'style': self.style})

class PlaceEdit(RoomGenericAPIView):
    template_name = 'place_edit.html'
    required_groups = REQ_GROUPS_PLACE

    def get(self, request, number):
        place = get_object_or_404(Room, number=number)
        serializer = PlaceSerializer(instance=room)
        return Response({'serializer': serializer, 'place': place, 'style': self.style})

    def post(self, request, number):  # HTML PUT and DELETE workaround
        method = request.POST.get("method", "")  # hidden input in forms, two buttons
        if method == 'PUT':
            return self.put(request, number)
        elif method == 'DELETE':
            instance = get_object_or_404(Room, number=number)
            place_number = instance.number
            if Booking.objects.filter(rooms=instance).exists():
                messages.warning(request, f'Place {place_number} is used by at least one booking and cannot be deleted!')
                return redirect('/places/')
            instance.delete()
            messages.success(request, f'Place {place_number} successfully deleted!')
            return redirect('/places/')
        messages.warning(request, f'Unknown method')
        return redirect('/places/')

    def put(self, request, number):
        instance = get_object_or_404(Place, number=number)
        serializer = PlaceSerializer(instance=instance, data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            messages.success(request, f'Place {instance.number} successfully edited!')
            return redirect('/places/')
        return Response({'serializer': serializer, 'style': self.style})


class BookingList(BookingGenericAPIView):
    template_name = 'bookings.html'
    required_groups = REQ_GROUPS_BOOKINGS

    def get(self, request):
        queryset = Booking.objects.all()
        return Response({'bookings': queryset})


class BookingAdd(BookingGenericAPIView):
    template_name = 'book.html'
    required_groups = REQ_GROUPS_BOOKINGS

    def get(self, request):
        serializer = BookingSerializer
        return Response({'serializer': serializer, 'style': self.style, 'PLACE_PRICES': dumps(PLACE_PRICES)})

    def post(self, request):
        serializer = BookingSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save(user=self.request.user)
            messages.success(request, f'Booking successfully added!')
            return redirect('/bookings/')
        return Response({'serializer': serializer, 'style': self.style})

class BookingEdit(BookingGenericAPIView):
    template_name = 'booking_edit.html'
    required_groups = REQ_GROUPS_BOOKINGS_UPDATE

    def get(self, request, pk):
        booking = get_object_or_404(Booking, pk=pk)
        serializer = BookingSerializer(instance=booking)
        return Response({'serializer': serializer, 'booking': booking, 'style': self.style,
                         'PLACE_PRICES': dumps(PLACE_PRICES)})

    def post(self, request, pk):  # HTML PUT and DELETE workaround
        method = request.POST.get("method", "")  # hidden input in forms, two buttons
        if method == 'PUT':

ideass/templates/book.html
{% extends "layout.html" %}
{% block title %}
    Book a Place
{% endblock %}
{% block content %}
{% load rest_framework %}
<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="method" value="PUT">
    {% render_field serializer.surname style=style %}
    {% render_field serializer.places style=style %}
    {% render_field serializer.check_in style=style %}
    {% render_field serializer.check_out style=style %}
    <div>
        <span>Days: </span><span id="days">Select dates</span><br>
        <span>Price: </span><span id="price">0</span>$
    </div>
    <button type="submit" class="btn btn-success my-1">Book</button>
</form>
<div>

</div>


<script>
$(document).ready(function() {
    var prices = {{ PLACE_PRICES|safe }};
    get_days_and_price(prices);
});
</script>

{% endblock %}

ideass/templates/booking_edit.html
{% extends "layout.html" %}
{% block title %}
    Booking Details - ID: {{ booking.id }}
{% endblock title %}
{% block content %}

{% load rest_framework %}
<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="method" value="PUT">
    {% render_field serializer.surname style=style %}
    {% render_field serializer.places style=style %}
    {% render_field serializer.check_in style=style %}
    {% render_field serializer.check_out style=style %}
    <div>
        <span>Days: </span><span id="days">Select dates</span><br>
        <span>Price: </span><span id="price">0</span>$
    </div>
    <button type="submit" class="btn btn-success my-1">Update Booking</button>
</form>
<form action="" method="POST">
    
    <input type="hidden" name="method" value="DELETE">
    <button type="submit" class="btn btn-danger">Delete Booking</button>
</form>

<script>
$(document).ready(function() {
    var prices = {{ PLACE_PRICES|safe }};
    get_days_and_price(prices)
    $("[name='check_in'], [name='check_out'], [name='places']").trigger("change");
});
</script>


{% endblock %}

ideass/templates/bookings.html
{% extends "layout.html" %}
{% block title %}
    Booking List
{% endblock %}
{% block content %}
    {% if user.is_place_client %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">#</th>
                        <th scope="col" class="text-center">DB ID</th>
                        <th scope="col" class="text-center">User</th>
                        <th scope="col" class="text-center">Surname</th>
                        <th scope="col" class="text-center">Rooms</th>
                        <th scope="col" class="text-center">Check In</th>
                        <th scope="col" class="text-center">Check Out</th>
                        <th scope="col" class="text-center">Days</th>
                        <th scope="col" class="text-center">Price</th>
                        <th scope="col" class="text-center">Created</th>
                        <th scope="col" class="text-center"></th>
                        <th scope="col" class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for booking in bookings %}
                    <tr>
                        <th scope="row" class="text-center">{{ forloop.counter }}</th>
                        <th scope="col" class="text-center">{{ booking.id }}</th>
                        <th scope="col" class="text-center">{{ booking.user }}</th>
                        <th scope="col" class="text-center">{{ booking.surname }}</th>
                        <th scope="col" class="text-center">{{ booking.get_place }}</th>
                        <th scope="col" class="text-center">{{ booking.check_in|date:"d/m/Y" }}</th>
                        <th scope="col" class="text-center">{{ booking.check_out|date:"d/m/Y" }}</th>
                        <th scope="col" class="text-center">{{ booking.get_booking_time }}</th>
                        <th scope="col" class="text-center">{{ booking.get_booking_price }}$</th>
                        <th scope="col" class="text-center">{{ booking.created|date:"d/m/Y H:i" }}</th>
                        <th scope="col"><form action="{% url 'ideass:bookings' %}{{booking.id}}/" method="GET">
                                            <input type="hidden" name="method" value="EDIT">
                                            <button type="submit" >Edit</button>
                                        </form></th>
                        <th scope="col"><form action="{% url 'ideass:bookings' %}{{booking.id}}/" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="method" value="DELETE">
                                            <button type="submit" class="btn btn-danger py-0">Delete</button>
                                        </form></th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">#</th>
                        <th scope="col" class="text-center">User</th>
                        <th scope="col" class="text-center">Surname</th>
                        <th scope="col" class="text-center">Places</th>
                        <th scope="col" class="text-center">Check In</th>
                        <th scope="col" class="text-center">Check Out</th>
                        <th scope="col" class="text-center">Days</th>
                        <th scope="col" class="text-center">Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for booking in bookings %}
                    <tr class="{% if booking.user == user %} text-success {% endif %}">
                        <th scope="row" class="text-center">{{ forloop.counter }}</th>
                        <th scope="col" class="text-center">
                            {% if booking.user == user %}
                                {{ booking.user }}
                            {% else %}
                                ***
                            {% endif %}
                        </th>
                        <th scope="col" class="text-center">
                            {% if booking.user == user %}
                                {{ booking.surname }}
                            {% else %}
                                ***
                            {% endif %}
                        </th>
                        <th scope="col" class="text-center">{{ booking.get_place }}</th>
                        <th scope="col" class="text-center">{{ booking.check_in|date:"d/m/Y" }}</th>
                        <th scope="col" class="text-center">{{ booking.check_out|date:"d/m/Y" }}</th>
                        <th scope="col" class="text-center">{{ booking.get_booking_time }}</th>
                        <th scope="col" class="text-center">
                            {% if booking.user == user %}
                                {{ booking.get_booking_price }}$
                            {% else %}
                                ***
                            {% endif %}
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if user.is_place_client %}
            <div class="text-center">
                This is the list of all our bookings.<br>
                Your ones are marked <span class="text-success">green.</span>
                <p>Only staff can make edits.</p>
            </div>
            {% endif %}
        </div>
    {% endif %}
    {% if not user.is_authenticated %}
    <div class="text-center">Log in to book a place!</div>
    {% endif %}
{% endblock %}

ideass/templates/change.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

ideass/templates/home.html
{% extends "layout.html" %}
{% block title %}
    Reservation Management System
{% endblock title %}
{% block content %}


<ul>
    <h4>Front end:</h4>
    Użytkownik niezalogowany:
    <li>- może zobaczyć listę wszystkich miejsc parkingowych</li>
    <li>- może zobaczyć listę wszystkich rezerwacji z zakrytymi danymi</li>
</ul>

<ul>
    Użytkownik zalogowany (Client):
    <li>- może zobaczyć listę wszystkich miejsc parkingowych</li>
    <li>- może zobaczyć listę wszystkich rezerwacji z zakrytymi danymi innych użytkowników</li>
    <li>- może tworzyć nowe rezerwacje</li>
</ul>

<ul>
    Użytkownik zalogowany (Staff):
    <li>- może zobaczyć listę wszystkich miejsc oraz rezerwacji z odkrytymi danymi</li>
    <li>- może tworzyć nowe oraz edytować i usuwać dowolne rezerwacje i miejsca</li>
    <li>- może wyszukiwać rezerwacje wg. wybranych kryteriów</li>
</ul>


{% endblock %}

ideass/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reservation place</title>

    {% load static %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">
    <link rel="stylesheet" type="text/css" href="{% static 'reset.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'script.js' %}"></script>
</head>
<body>

{% load tags %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ideass:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ideass:bookings' %}">Booking List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ideass:places' %}">Place List</a>
                    </li>

              
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ideass:book' %}">Create Booking</a>
                        </li>
                    {% endif %}
                    {% if user.is_hotel_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ideass:place_add' %}">Add a Room</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ideass:search' %}">Search</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schema-swagger-ui' %}">API</a>
                    </li>
                </ul>
            </div>
            <div class="mx-auto order-0">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-primary">Logged as {{ user.get_username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="{% url 'ideass:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ideass:login' %}">Login</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ideass:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div>
        <h1 class="mt-2">
            {% block title %}
            {% endblock %}
        </h1>
    </div>
    <div class="wrapper">
        <div class="wrapper-item">

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags %}
                        <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

ideass/templates/place_add.html
{% extends "layout.html" %}
{% block title %}
    Add a Place
{% endblock %}
{% block content %}
{% load rest_framework %}
<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="method" value="PUT">
    {% render_field serializer.number style=style %}
    {% render_field serializer.category style=style %}
    <button type="submit" class="btn btn-success my-1">Save</button>
</form>

{% endblock %}

ideass/templates/places.html
{% extends "layout.html" %}
{% block title %}
    Place List
{% endblock %}
{% block content %}
    {% if user.is_hotel_staff %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">#</th>
                        <th scope="col" class="text-center">Number</th>
                        <th scope="col" class="text-center">Class</th>
                        <th scope="col" class="text-center"></th>
                        <th scope="col" class="text-center"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for place in places %}
                    <tr>
                        <th scope="row" class="text-center">as{{ forloop.counter }}</th>
                        <th scope="col" class="text-center">aaasss{{ place.number }}</th>
                        <th scope="col" class="text-center">aaaaaaassssss{{ place.get_category }}</th>
                        <th scope="col"><form action="{% url 'ideass:places' %}{{place.number}}/" method="GET">
                                            <input type="hidden" name="method" value="EDIT">
                                            <button type="submit" class="btn btn-success py-0">Edit</button>
                                        </form></th>
                        <th scope="col"><form action="{% url 'ideass:places' %}{{place.number}}/" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="method" value="DELETE">
                                            <button type="submit" class="btn btn-danger py-0">Delete</button>
                                        </form></th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
         <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">#</th>
                        <th scope="col" class="text-center">Number</th>
                        <th scope="col" class="text-center">Class</th>
                    </tr>
                </thead>
                <tbody>
                    {% for place in places %}
                    <tr>
                        <th scope="row" class="text-center">{{ forloop.counter }}</th>
                        <th scope="col" class="text-center">{{ place.number }}</th>
                        <th scope="col" class="text-center">{{ place.get_category }}</th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    {% if not user.is_hotel_staff %}
    <div class="text-center">This is the list of all our places.</div>
    {% endif %}
{% endblock %}